### ISSUE TITLE
Can't connect because context.constructors.ClientConnection doesn't exist

### ISSUE THREAD

**Issue by jenow** [kuzzleio/kuzzle-plugin-mqtt#12]
An error is thrown by the plugin when a client try to connect:

TypeError: this.context.constructors.ClientConnection is not a constructor
at MqttProtocol.onConnection (/var/app/plugins/available/kuzzle-plugin-mqtt/lib/index.js:108:26)

**Comment by dbengsch** [comment]
It seams everything is all right (The example provided in the README works as expected). But the documentation of the proxy's plugin context seams really outdated. I will create an issue in the documentation.
